#!/usr/bin/env bash

main() {
	set -euo pipefail

	[[ "${TRACE:-}" != '' ]] && set -x

	for branch in f{29..31} epel7; do
		mr -q mergemaster "$branch"
	done

	mr -q run git checkout master
}

[[ "$0" == "${BASH_SOURCE[0]}" ]] && main "$@"
