#!/usr/bin/env bash

# shellcheck source=./promote-update
. "$(dirname "${BASH_SOURCE[0]}")/promote-update"

_get_certbot_updates() {
	local release="$1" status="${2:-testing}"
	_get_updates "$release" '' "$status" |
		sort |
		sed -nEf <(cat <<-'SCRIPT'
			/^python-acme/ { # print python-acme updates first
				p
				d
			}
			H # put other updates into the hold space
			$ { # at EOF, print the hold space
				x
				s/^\n//mg # filter out blank lines
				p
			}
		SCRIPT
		)
}

main() {
	set -euo pipefail

	[[ "${TRACE:-}" != '' ]] && set -x

	if [[ "$#" -lt 1 ]]; then
		echo 'Usage: promote-updates release [status]'
		return 64
	fi

	local release="$1" status="${2-stable}"
	local update

	while IFS= read -r update; do
		_promote_update "$update" "$status"
	done < <(_get_certbot_updates "$release")

	_promote_updates "$release" "$package" testing "$status"
}

[[ "$0" == "${BASH_SOURCE[0]}" ]] && main "$@"
