#!/usr/bin/env bash

main() {
	set -euo pipefail

	[[ "${TRACE:-}" != '' ]] && set -x

	for branch in f{28..30} epel7; do
		mr build "$branch"
	done

	mr -q run git checkout master
}

[[ "$0" == "${BASH_SOURCE[0]}" ]] && main "$@"
